# teams are in a yml file so they can easily be changed.
teams:
  red:
    name: "Red Raptors"
    color: "RED"
  orange:
    name: "Coral Carnotaurs"
    color: "GOLD"
  yellow:
    name: "Dandelion Dimetrodons"
    color: "YELLOW"
  mint:
    name: "Mint Mammoths"
    color: "GREEN"
  green:
    name: "Green Gallimimus"
    color: "DARK_GREEN"
  teal:
    name: "Teal Triceratops"
    color: "AQUA"
  turquoise:
    name: "Turquoise Tyrannosaurs"
    color: "DARK_AQUA"
  blue:
    name: "Sapphire Spinosaurs"
    color: "BLUE"
  purple:
    name: "Amethyst Ankylosaurs"
    color: "DARK_PURPLE"
  pink:
    name: "Salmon Stegosaurs"
    color: "LIGHT_PURPLE"